spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matilda?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 771662
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
server:
  port: 8088
  servlet:
    context-path: /app

