spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.157:3306/qiche
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  data:
    mongodb:
      uri: mongodb://192.168.1.157:27017/1807b
  redis:
    password:
    database: 0
    timeout: 0
    host: 192.168.1.157
    port: 6379

    solr:
      host: http://127.0.0.1:8082/solr
server:
  port: 8088
  servlet:
    context-path: /app

mybatis:
  typeAliasesPackage: com.jk.model
  mapperLocations: classpath:mapper/*.xml
