spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.157:3306/qiche
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
server:
  port: 8088
  servlet:
    context-path: /app

